
# ========================================
# CONFIGURATION DE L'APPLICATION
# ========================================
spring:
  application:
    name: mobilite
  profiles:
    active: prod
  # ========================================
  # CONFIGURATION DE LA BASE DE DONNÉES
  # ========================================
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:mobilite}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pnd0892}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 20000
      validation-timeout: 5000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
  # ========================================
  # CONFIGURATION JPA
  # ========================================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # ✅ 4 espaces
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform



# ========================================
# CONFIGURATION JWT / SÉCURITÉ
# ========================================

jwt:
  header: Authorization
  prefix: "Bearer "
  secret: 9d5d0000ced4ba0959fb6efb6853aa5e4e2d3408a624ee236bfa62baffdf487eef96b29127ee533d110efd3c9a5d6bd043e2e6f69bfd66b450b45f9d3cfa1d5b
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

# ========================================
# CONFIGURATION LOGGING
# ========================================
logging:
  level:
    root: INFO
    com.techinnov.consulaire: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration: ERROR  # Pour masquer l'avertissement open-in-view
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

